services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env.prod
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: django
    build:
      context: .
      dockerfile: ./django/Dockerfile.prod
    command: sh -c "npm run build &&
              python django/manage.py collectstatic --noinput &&
              python django/manage.py makemigrations &&
              python django/manage.py migrate &&
              gunicorn gohanMTG.wsgi:application --chdir django --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/nginx/static/
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      db: 
        condition: service_healthy
  web:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    volumes:
      - static_volume:/code/nginx/static/
    ports:
      - "80:80"

volumes:
  static_volume: