services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: gohanmtg-db-${AZ}
        awslogs-create-group: "true"
  app:
    build:
      context: .
      dockerfile: ./django/Dockerfile.prod
    volumes:
      - .:/code
      - static_volume:/code/nginx/static/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db: 
        condition: service_healthy
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: gohanmtg-app-${AZ}
        awslogs-create-group: "true"
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    volumes:
      - static_volume:/code/nginx/static/
    ports:
      - "80:80"
    depends_on:
      - app
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: gohanmtg-web-${AZ}
        awslogs-create-group: "true"


volumes:
  static_volume: