
services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: django
    build:
      context: .
      dockerfile: ./django/Dockerfile
    command: sh -c "npm run watch &
              python django/manage.py migrate &&
              python django/manage.py create_dev_superuser &&
              python django/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db: 
        condition: service_healthy