FROM python:3.12

ARG UID=1000
ARG GID=1000

ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY ./requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y gosu

RUN groupadd -g $GID mygroup && useradd -m -u $UID -g $GID myuser

COPY ./docker-entrypoint.sh /code/
RUN chmod +x /code/docker-entrypoint.sh

COPY . /code

ENTRYPOINT ["/code/docker-entrypoint.sh"]